# Generates baked_server.h with the lobby server address lightly obscured,
# so the release binary carries it without it appearing as a plain string,
# and so it never has to live in the repository: pass it at configure time
# with -DSF4E_BAKED_SERVER=host[:port], typically from deploy/server.private.
#
# The encoding is a rolling XOR: byte i of the address is stored as
# (byte XOR (0x5A + i)). It is not secrecy, only opacity; anyone with the
# binary and the will can read it. The point is that it isn't in a text
# file next to the launcher and doesn't show up in a strings dump.

set(_out "${SF4E_BAKED_OUT}")
set(_addr "${SF4E_BAKED_SERVER}")

# Printable ASCII, used to turn characters into codes; CMake has no ord().
set(_table " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~")

string(LENGTH "${_addr}" _len)
set(_bytes "")
set(_i 0)
while(_i LESS _len)
  string(SUBSTRING "${_addr}" ${_i} 1 _ch)
  string(FIND "${_table}" "${_ch}" _idx)
  if(_idx LESS 0)
    message(FATAL_ERROR "SF4E_BAKED_SERVER contains a character outside printable ASCII")
  endif()
  math(EXPR _code "${_idx} + 32")
  math(EXPR _key "(90 + ${_i}) % 256")
  math(EXPR _enc "${_code} ^ ${_key}")
  string(APPEND _bytes "${_enc},")
  math(EXPR _i "${_i} + 1")
endwhile()

file(WRITE "${_out}" "// Generated by cmake/bake-server.cmake. Do not edit or commit.\n")
file(APPEND "${_out}" "#pragma once\n")
file(APPEND "${_out}" "static const unsigned char SF4E_BAKED_SERVER_BYTES[] = { ${_bytes} 0 };\n")
file(APPEND "${_out}" "static const unsigned int SF4E_BAKED_SERVER_LEN = ${_len};\n")
